name: Ci pipe

on:
  push:
    branches: [main]

env:
  APP_ENV: production

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod        # где хранятся Go зависимости
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Run test
        run: go test -v ./...
      - name: Print produc name 
        run: echo $APP_ENV 
  
  docker:
      needs: build
      runs-on: ubuntu-latest

      steps:
        - name: Copy Repo
          uses: actions/checkout@v4

        - name: LOGIN into docker hub!
          uses: docker/login-action@v4
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: Build and push
          uses: docker/build-push-action@v5
          with: 
            context: ./app
            push: true
            tags: whosthefunky/cicd-practice:${{ github.sha }}
  terraform:
    needs: build
    runs-on: ubuntu-latest
  
    defaults:
      run:
        working-directory: infra/dev

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
      - name: AWS creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve
  deploy:
    needs: [docker, terraform]
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker pull whosthefunky/cicd-practice:${{ github.sha }}
            docker stop app || true
            docker rm app || true
            docker run -d \
              --name app \
              -p 80:8080 \
              whosthefunky/cicd-practice:${{ github.sha }}